// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NegativeTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC003InvalidEmailSubmission() {
    driver.get("https://www.tourslanka.com/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Contact")).click();
    driver.findElement(By.name("yourname")).click();
    driver.findElement(By.name("yourname")).sendKeys("Tester");
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("0756625289");
    driver.findElement(By.name("your-email")).click();
    driver.findElement(By.name("your-email")).sendKeys("testergmail.com");
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".wpcf7-not-valid-tip")));
    }
    assertThat(driver.findElement(By.cssSelector(".wpcf7-not-valid-tip")).getText(), is("The e-mail address entered invalid."));
    driver.findElement(By.name("country")).click();
    {
      WebElement dropdown = driver.findElement(By.name("country"));
      dropdown.findElement(By.xpath("//option[. = 'Sri Lanka']")).click();
    }
    driver.findElement(By.name("message")).click();
    driver.findElement(By.name("message")).sendKeys("it is a testing");
    driver.findElement(By.cssSelector(".wpcf7-submit")).click();
  }
@Test
public void tC005Emptyinput() {
    driver.get("https://www.tourslanka.com/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Contact")).click();
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("0777676758");
    driver.findElement(By.cssSelector(".wpcf7-submit")).click();
    assertThat(driver.findElement(By.cssSelector(".wpcf7-not-valid-tip")).getText(), is("The field is required"));
    driver.findElement(By.cssSelector(".row:nth-child(4)")).click();
    driver.findElement(By.name("your-email")).sendKeys("tester@gmail.com");
    WebElement dropdown = driver.findElement(By.name("country"));
    dropdown.findElement(By.xpath("//option[. = 'Sri Lanka']")).click();
    driver.findElement(By.name("message")).click();
    driver.findElement(By.name("message")).sendKeys("it is a testing");
    driver.findElement(By.cssSelector(".wpcf7-submit")).click();
}
}
